------------------------------------------ CPP HIGHLIGHTS ------------------------------------------

return {
  ['@attribute.cpp'] = { link = 'Operator' },
  ['@character.cpp'] = { link = 'String' },
  ['@constant.builtin.cpp'] = { link = 'Constant' },
  ['@define.cpp'] = { link = 'Operator' },
  ['@field.cpp'] = { link = 'Field' },
  ['@function.builtin.cpp'] = { link = 'Operator' },
  ['@include.cpp'] = { link = 'Include' },
  ['@keyword.directive.cpp'] = { link = 'Operator' },
  ['@namespace.cpp'] = { link = 'Namespace' },
  ['@parameter.cpp'] = { link = 'Parameter' },
  ['@property.cpp'] = { link = 'Field' },
  ['@preproc.cpp'] = { link = 'Include' },
  ['@repeat.cpp'] = { link = 'Keyword' },
  ['@string.escape.cpp'] = { link = 'Operator' },
  ['@storageclass.cpp'] = { link = 'Operator' },
  ['@type.builtin.cpp'] = { link = 'Keyword' },
  ['@type.qualifier.cpp'] = { link = 'Operator' },
  ['@variable.builtin.cpp'] = { link = 'Keyword' },

  ['@lsp.type.enumMember.cpp'] = { link = 'Field' },
  ['@lsp.type.namespace.cpp'] = { link = 'Namespace' },
  ['@lsp.type.parameter.cpp'] = { link = 'Parameter' },
  ['@lsp.type.operator.cpp'] = { link = 'Operator' },
  ['@lsp.type.property.cpp'] = { link = 'Field' },
  ['@lsp.typemod.class.deduced.cpp'] = { link = 'Keyword' },
  ['@lsp.typemod.operator.declaration.cpp'] = { link = 'Function' },
  ['@lsp.typemod.operator.userDefined.cpp'] = { link = 'Keyword' },
  ['@lsp.typemod.variable.classScope.cpp'] = { link = 'Field' },
}
