----------------------------------------- RUST HIGHLIGHTS ------------------------------------------

return {
  rustCharacter = { link = 'String' },
  rustEnumVariant = { link = 'Field' },
  rustLifetime = { link = 'Keyword' },
  rustModPath = { link = 'Namespace' },
  rustQuestionMark = { link = 'Operator' },
  rustSelf = { link = 'Keyword' },
  rustSigil = { link = 'Operator' },
  rustStorage = { link = 'Keyword' },

  ['@character.rust'] = { link = 'String' },
  ['@include.rust'] = { link = 'Include' },
  ['@field.rust'] = { link = 'Field' },
  ['@namespace.rust'] = { link = 'Namespace' },
  ['@storageclass.rust'] = { link = 'Keyword' },
  ['@storageclass.lifetime.rust'] = { link = 'Keyword' },
  ['@string.escape.rust'] = { link = 'Operator' },
  ['@type.qualifier.rust'] = { link = 'Keyword' },
  ['@variable.builtin.rust'] = { link = 'Keyword' },

  ['@lsp.type.builtinType.rust'] = { link = 'Type' },
  ['@lsp.type.character.rust'] = { link = 'String' },
  ['@lsp.type.enumMember.rust'] = { link = 'Field' },
  ['@lsp.type.escapeSequence.rust'] = { link = 'Operator' },
  ['@lsp.type.keyword.rust'] = { link = 'Keyword' },
  ['@lsp.type.label.rust'] = { link = 'Operator' },
  ['@lsp.type.lifetime.rust'] = { link = 'Keyword' },
  ['@lsp.type.namespace.rust'] = { link = 'Namespace' },
  ['@lsp.type.number.rust'] = { link = 'Constant' },
  ['@lsp.type.parameter.rust'] = { link = 'Parameter' },
  ['@lsp.type.property.rust'] = { link = 'Field' },
  ['@lsp.type.selfKeyword.rust'] = { link = 'Keyword' },
  ['@lsp.type.selfTypeKeyword.rust'] = { link = 'Type' },
  ['@lsp.type.typeAlias.rust'] = { link = 'Type' },
}
