name: Bug Report
description: File a bug / issue with midnight.nvim
title: "bug: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        **Before** reporting an issue, make sure to read the
        [documentation](https://github.com/dasupradyumna/midnight.nvim) and search through
        [existing issues](https://github.com/dasupradyumna/midnight.nvim/issues). Usage questions
        such as ***"How do I...?"*** belong in
        [Discussions](https://github.com/dasupradyumna/midnight.nvim/discussions) and will be closed.
  - type: checkboxes
    attributes:
      label: Did you check documentation and existing issues?
      description: Make sure you have checked all of the below checkboxes before submitting an issue
      options:
        - label: I have read all the midnight.nvim documentation
          required: true
        - label: I have searched through all existing issues of midnight.nvim
          required: true
        - label: My issue is non-trivial and does not belong in the Discussions section
          required: true
  - type: input
    attributes:
      label: "Neovim version (nvim -v)"
      placeholder: |
        "NVIM v0.10.0-dev
        Build type: RelWithDebInfo
        LuaJIT 2.1.0-beta3"
    validations:
      required: true
  - type: input
    attributes:
      label: "Operating system / version (for eg., uname -sro)"
      placeholder: "Linux 5.15.0-75-generic GNU/Linux"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is. Please include any related errors you
        see in Neovim.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Repro
      description: |
        Minimal `init.lua` to reproduce this issue. Save as `repro.lua` and run `nvim -u repro.lua`
      value: |
        -- DO NOT change the paths
        local root = vim.fn.fnamemodify("./.repro", ":p")

        -- set stdpaths to use .repro
        for _, name in ipairs({ "config", "data", "state", "cache" }) do
          vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
        end

        -- bootstrap lazy
        local lazypath = root .. "/plugins/lazy.nvim"
        if not vim.loop.fs_stat(lazypath) then
          vim.fn.system {
            "git",
            "clone",
            "--filter=blob:none",
            "https://github.com/folke/lazy.nvim.git",
            lazypath,
          }
        end
        vim.opt.runtimepath:prepend(lazypath)

        -- install plugins
        require("lazy").setup({
          {
            "dasupradyumna/midnight.nvim",
            lazy = false,
            priority = 1000,
            config = function()
              require('midnight').setup {
                --- add code here
              }
            end,
          }
        }, { root = root .. "/plugins" })

        vim.cmd.colorscheme "midnight"
      render: Lua
    validations:
      required: false
